### ISSUE TITLE
Fix tables not showing up

### ISSUE THREAD

**Issue by RangerDevv** [RangerDevv/ReWrit#5]
Fix table borders not showing up

**Comment by RangerDevv** [comment]
Issue resolved by adding the following code: 

```css
    /* style table  with a white border */
    table {
        border: 1px solid white;
    }
    /* style table header with a white border */
    th {
        border: 1px solid white;
    }
    /* style table body with a white border */
    td {
        border: 1px solid white;
    }
```
